# Generated by Django 5.2.3 on 2025-07-01 10:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 1MB, formats: JPG, PNG, GIF)', null=True, upload_to=accounts.models.user_profile_picture_path, validators=[accounts.models.validate_image_size, accounts.models.validate_image_format]),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
