# Generated by Django 5.2.3 on 2025-07-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpostreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
    ]
