# Generated by Django 5.2.3 on 2025-07-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategory_blogtag_blogpost_category_blogcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='BlogTag',
        ),
    ]
