name: Build and deploy Python app to Azure Web App - PlantParent

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static (build time)
        env:
          DJANGO_SETTINGS_MODULE: plantparent.settings
          SECRET_KEY: dummy-secret
          DEBUG: "False"
          ALLOWED_HOSTS: plantparent-buexaefjfkhvfgey.italynorth-01.azurewebsites.net
          CSRF_TRUSTED_ORIGINS: https://plantparent-buexaefjfkhvfgey.italynorth-01.azurewebsites.net
        run: |
          python manage.py collectstatic --noinput
          ls -lah staticfiles/videos || true

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !.git/
            !**/__pycache__/
            !**/*.pyc

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_37E743316F3A43E5A60A05FFF5289867 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D73D0BA8F692406E9AA34F6F0432E96D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AAF2E2D25B7C4A80B665B7308B9FBD07 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "PlantParent"
          slot-name: "Production"
          package: "."
