name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # или версията, която ползваш локално

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install django; fi

     
      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: PlantParent.settings   # <-- смени с твоите settings ако е друго
          SECRET_KEY: dummy-secret-key
          DEBUG: "0"
        run: |
          python manage.py migrate --noinput

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: PlantParent.settings   # <-- смени ако е друго
          SECRET_KEY: dummy-secret-key
          DEBUG: "0"
        run: |
          python manage.py test -v 2
